spring.application.name=localProblemSolver
spring.datasource.url = jdbc:mysql://localhost:3306/complaint_system?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = Aryan@123
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
gemini.api.key=${GEMINI_API_KEY}
jwt.secret= Aryan@1234567890987yhgjftyhgvbgdrtfgyhju7@%ec=8!@34r56_((7yy65yuuuuuutyi__=
jwt.expiration=86400000

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE 
logging.level.org.springframework.transaction=DEBUG